keys:
  system76-pc: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG76ujCICLpUlhfcNvPRK2ZbbIMxLvl2Y900Prx9E3Cr
  desktop: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/etrDU35s7qB0xuulD2zk16/GGqrRPymhiY8hHcH6LXqk93b9BoflC9s8VzVbFUS4p2vgLpEeaH78DxFbkRP49UrFKC7OH49qEsB0u/n8OIE+dBhPBFUzL2nKJu8S7JEO5xzHi0RNQ6/NkP+0wDNv4WRBcywqdAcyvHyZRM3KPZzVgRMa3eN+vv1NvWPk4r31rEGRrXWfKHR0b4aow0982gUeiUvDPNlESpeVFTO0JTHKt9ERuPg0jusiSEh5S7O/aQJhHs33B/lkK29+1K8JaFtEtb9o/2DT5OZPJ1kkKS67lV89H4PwwXEiRQ64KXDIuxsYfq2B6FXWGy9DJOaXGS4v/vd12PyqPWIAAg5yz8FWUgxfCEQxICb/V197I6vaA4i1EWqIWSQ1CW6GoYsenIfxV23QrxPuW+OgVcGSVj04MzfExMIS1B0Z9h+MREkXmBhJyfN68yhwr7fecqI0LU9BvkP59sPzfvQq0y8yOv5mYkIvli5d4Z986q8a048=
  old_server: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFdCwcurC4Duw+dKudf8aTIAXzalVnyEJa9RdIUDH+lG
server_type: cx32
location: fsn1
