name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: |
          terraform init
          terraform apply -input=false -auto-approve
        name: Terraform apply
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
