name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull tf state
        run: |
          git fetch origin tfstate || echo "tfstate branch does not exist"
          if git show-ref --verify --quiet refs/remotes/origin/tfstate; then
            if git ls-tree --name-only origin/tfstate | grep -q '^terraform.tfstate.enc$'; then
              git checkout origin/tfstate -- terraform.tfstate.enc
              openssl aes-256-cbc -pbkdf2 -d -in terraform.tfstate.enc -out terraform.tfstate -pass pass:${{ secrets.TF_STATE_PASSWORD }}
            else
              echo "Encrypted terraform.tfstate.enc file not found in tfstate branch"
            fi
          else
            echo "tfstate branch not found, skipping state download"
          fi

      - uses: hashicorp/setup-terraform@v3

      - run: |
          terraform init
          terraform apply -input=false -auto-approve
        name: Terraform apply
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: Push tf state
        if: always()
        run: |
          openssl aes-256-cbc -pbkdf2 -salt -in terraform.tfstate -out terraform.tfstate.enc -pass pass:${{ secrets.TF_STATE_PASSWORD }}
          git pull origin tfstate || true
          git checkout tfstate || git checkout -b tfstate
          git add terraform.tfstate.enc
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "Update tfstate" || echo "No changes"
          git push origin tfstate
